name: frontend
description: PawJeevan - Pet Store & AI Care Platform
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For Material Design icons
  cupertino_icons: ^1.0.6

  # State Management
  provider: ^6.1.2

  # Networking
  dio: ^5.4.1

  # Local Storage for tokens, settings, etc.
  shared_preferences: ^2.2.2

  # Image Picking (from gallery/camera)
  image_picker: ^1.2.0
  flutter_image_compress: ^2.0.0

  # Launching URLs (for email feedback)
  url_launcher: ^6.3.2

  # Date formatting
  intl: ^0.18.1

  timezone: ^0.9.2

  timeago: ^3.7.1
  
  # Google Sign-In
  google_sign_in: ^6.1.0
  
  # SVG support for logos
  flutter_svg: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code quality and style guide
  flutter_lints: ^3.0.1
  
  # App icon generator
  flutter_launcher_icons: ^0.13.1

# App Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/pawjeevan.png"
  min_sdk_android: 21
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/data/countries_cities.json
    - assets/data/facts.json